env: "local"
path_to_private_key: "C:\\Users\\temat\\.ssh\\openssh_private"
database:
  address: "localhost"
  port: 32768
  user: "postgres"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s