name: Check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - name: Install Maven
        run: |
         sudo apt update
         sudo apt install maven
      - name: Run tests
        run: |
	 cd skvdb-api-spec
	 mvn install
	 cd ../skvdb
         mvn test
