name: Build and Deploy
on: push
jobs:
  build_skvdb_manager_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd frontend
          docker build -t skvdb-manager-frontend .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag skvdb-manager-frontend:latest ${{ secrets.DOCKER_USERNAME }}/skvdb-manager-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/skvdb-manager-frontend:latest
